### ISSUE TITLE
Root module outputs wrong `vault_lb_addr`

### ISSUE THREAD

**Issue by terorie** [terraform-google-modules/terraform-google-vault#101]
It looks like the output `vault_lb_addr` doesn't match its description.

https://github.com/terraform-google-modules/terraform-google-vault/blob/ff2003290d615b8d010c6c1300548f4742c00470/outputs.tf#L38-L46

An example output of `vault_addr` is `https://10.127.0.2:8200` ("Full protocol, address, and port (FQDN) pointing to the Vault load balancer")

However, so is `vault_lb_addr`: It's also `https://10.127.0.2:8200`. I would expect it to be `10.127.0.2`. ("Address of the load balancer without port or protocol information.")

Perhaps the `vault_lb_addr` output in the root module meant to export the `vault_lb_addr` output in the sub-module instead?

**Comment by terorie** [comment]
Fix available at #102

**Comment by onetwopunch** [comment]
#102 merged. Thanks for submitting this issue.

**Comment by onetwopunch** [comment]
This is released in `v5.0.1`
