### ISSUE TITLE
'terraform destroy' blocked by inability to delete bucket

### ISSUE THREAD

**Issue by jai** [terraform-google-modules/terraform-google-vault#111]
When running 'destroy' on Terraform Cloud, it seems the bucket always blocks the destruction. Is this expected or is this a misconfiguration on my part?

```
Error: Error trying to delete bucket <NAME>-vault-data containing objects without `force_destroy` set to true.
```

**Comment by onetwopunch** [comment]
You can set `storage_bucket_force_destroy` to `true` which should allow you to destroy the bucket even if there's objects in it. This is set to false by default to prevent accidentally wiping out Vault data
