### ISSUE TITLE
Not able to connect to vault

### ISSUE THREAD

**Issue by sharadjain21** [terraform-google-modules/terraform-google-vault#112]
Hi Team

I had used the module and created vault. which is visible in google console.. though while trying to connect to it.. or while running vault status getting below issue.

$ vault status
Error checking seal status: Get "https://XX.XXX.XX.XXX:8200/v1/sys/seal-status": dial tcp XX.XXX.XX.XXX:8200: connectex: No connection could be made because the target machine actively refused it.

below is what i used for setting up vault on gcp

module "vault" {
source = "terraform-google-modules/vault/google"
version = "4.0.0"
project_id = var.gcp_project_id
region = var.region
kms_keyring = var.kms_keyring
kms_crypto_key = var.kms_crypto_key

storage_bucket_force_destroy = true
}

output "vault_addr" {
value = module.vault.vault_addr
}

**Comment by sharadjain21** [comment]
Got a clue on it.. the startup script is not working .. and when i run it manually on created VM then vault service becomes available and able to connect to VM. could someone please check why script is not working at the start.

**Comment by onetwopunch** [comment]
@sharadjain21 could you please provide more details on why the startup script is failing? We actually do run automated tests to ensure the startup script is working and Vault is reachable so there may be other issues with your configuration.
