### ISSUE TITLE
Couldn't parse PEM in ../tls/ca.pem file

### ISSUE THREAD

**Issue by talktomeg** [terraform-google-modules/terraform-google-vault#122]
Looks like there are no certificates written into the /tls directory but the terraform.tfstate has a few different certificates present. I copied the ca_cert into a separate file called ca.pem in /tls directory. And then tried

> $ export VAULT_CAPATH="$(cd ../ && pwd)/tls/ca.pem"

(also set the VAULT_ADDR and VAULT_TOKEN)

When I try to connect to vault server, 
I get the error  

> failed to read environment: Error loading CA Path: Couldn't parse PEM in: <fullpath>/terraform_scripts/vault-setup/tls/ca.pem

Any help would be appreciated! Thank you! This project has been very helpful!

**Comment by onetwopunch** [comment]
It will be hard to help you debug this issue without seeing the content of the PEM you are referring to, however, I can tell you that when specifying a CA file, you should use `VAULT_CACERT` not `VAULT_CAPATH`. It might be trying to interpret that pem file as a directory.
