### ISSUE TITLE
Remove google project reference so module can be used with count

### ISSUE THREAD

**Issue by symbiont-tony-moulton** [terraform-google-modules/terraform-google-vault#140]
### TL;DR

Remove the explicit provider configuration and allow it to be passed in when calling the module.

### Terraform Resources

```markdown
https://www.terraform.io/language/modules/develop/providers
```

### Additional information

Looking to deploy a dynamic series of resources each with their own vault cluster

**Comment by bharathkkb** [comment]
Thanks for the report @symbiont-tony-moulton 
Happy to review a PR for this

**Comment by symbiont-tony-moulton** [comment]
> Thanks for the report @symbiont-tony-moulton Happy to review a PR for this

Fantastic! I just submitted #141
