### ISSUE TITLE
is there a way to avoid "external" data source?

### ISSUE THREAD

**Issue by medyagh** [terraform-google-modules/terraform-google-vault#16]
https://github.com/GoogleCloudPlatform/terraform-google-vault/blob/86091ab37c4ab2287529f3f0276d0f895668164c/main.tf#L95

[Terraform docs](https://www.terraform.io/docs/providers/external/data_source.html) warns not to use external data source, (and they have even removed the link to it in the original docs about types of data source [providers](https://www.terraform.io/docs/providers/template/d/file.html#) , I was wondering was there a good reason to choose external data source?

**Comment by carlodicelico** [comment]
Actually, the way it's done here is also nice: https://github.com/matti/terraform-shell-resource. I might fold some of those ideas into the approach up there ☝️

**Comment by sethvargo** [comment]
I updated this a bit in #41, but whether you shell out to a script or shell out in a null_resource provisioner is basically the same. Unfortunately there's not a great way to solve this without adding a `kms_encrypt` resource into Terraform itself.
