### ISSUE TITLE
Debian 10 has been deprecated and removed

### ISSUE THREAD

**Issue by emanuelet** [terraform-google-modules/terraform-google-vault#210]
### TL;DR

https://cloud.google.com/compute/docs/images/os-details#debian
The debian 10 base image which is default of this repo has been deprecated and removed on the 30th of June

### Terraform Configuration

```hcl
module "vault" {
  vault_instance_base_image ="debian-cloud/debian-12"
}
```

### Terraform Version

```sh
Terraform v1.9.2
on linux_amd64
```

**Comment by dcb-imvaria** [comment]
I just encountered the same issue.

**Comment by dcb-imvaria** [comment]
Any progress on this issue?

**Comment by jogoldberg** [comment]
Any update on this?
