### ISSUE TITLE
Do we need more than 1 external IPs for the Cloud NAT

### ISSUE THREAD

**Issue by dcaba** [terraform-google-modules/terraform-google-vault#45]
In regards to:
https://github.com/terraform-google-modules/terraform-google-vault/blob/cfcd7b52e6bd77146544d9f952e8deda31953f3d/network.tf#L23

I think IPs are global, and Cloud NATs are regional (multizone), so I dont completetly understand why we want two NAT IPs for outbound traffic... probably Im missing something, but just in case we can change this...

**Comment by sethvargo** [comment]
IPs are globally routable, but these IPs in particular are regional IPs (they live within a region), but the main reason is for higher availability. You can safely change that to 1 and everything will still work.
