### ISSUE TITLE
Variable tls_ca_subject invalid default

### ISSUE THREAD

**Issue by RiFi2k** [terraform-google-modules/terraform-google-vault#47]
The default for the `tls_ca_subject` is throwing an error during validation.

```
This default value is not compatible with the variable's type constraint:
all map elements must have the same type.
```

The `street_address` in the map is an array and all the other values are strings. So I'm assuming that is the issue right there.

https://github.com/terraform-google-modules/terraform-google-vault/blob/master/variables.tf#L240

Running terraform v0.12.1

**Comment by RiFi2k** [comment]
Confirmed that changing that line from an array to a string fixes the issue for me.

**Comment by sethvargo** [comment]
See my comment on the PR. I'm going to close this issue and we can keep conversation on the PR 😄
