### ISSUE TITLE
Why my startup.sh.tpl does not run

### ISSUE THREAD

**Issue by xgu89** [terraform-google-modules/terraform-google-vault#49]
when i run "terraform apply" and it come complete, but startup.sh.tpl contents has not run, and  in VM instance detail page, I can see startup-script with the startup.sh.tpl contents, I don't know why startup.sh.tpl doesn't run. Can anyone help me with this issue, thanks!

**Comment by sethvargo** [comment]
Hi @xgu89 

Can you provide more information? What changes have you made to the Terraform modules? Do you see any errors if you SSH into the VM and run:

```sh
sudo journalctl -u google-startup-scripts.service
```

Note that the startup script runs on startup and can take 2-3 minutes to complete. Terraform will exit _before_ the startup scripts have completed.

**Comment by xgu89** [comment]
@sethvargo Thanks for reply, and now it works.
