### ISSUE TITLE
Spin up Vault cluster on custom network

### ISSUE THREAD

**Issue by chanux** [terraform-google-modules/terraform-google-vault#61]
I'm not sure if there are any security considerations or other reasons behind the creation of dedicated network/subnetwork in this module. Would like to know the reasons if there are any. Otherwise we can probably work on adding the ability to choose whether to use dedicated network or custom network.

**Comment by sethvargo** [comment]
Hi @chanux - in general, you want to isolate Vault as much as possible from other services. This is also mentioned in the [Vault hardening guide](https://learn.hashicorp.com/vault/operations/production-hardening). It's not a hard requirement, but Vault should really be on its own dedicated network/IP space and traffic to that network should be restricted behind a firewall.

Let me know if you have other questions.

**Comment by morgante** [comment]
@sethvargo I think the enterprise best practice is to use a Shared VPC so Vault can be connected over private space. It can still be restricted by firewall rules for the subnet or service account.

IMO it would make sense to allow this module to accept a custom network input.

**Comment by sethvargo** [comment]
@morgante wouldn't best practice be to run a dedicated VPC and then use VPC peering instead?

**Comment by sethvargo** [comment]
FWIW, I'm okay with this change, just trying to figure out what the "default" should be.

**Comment by morgante** [comment]
@sethvargo VPC peering has a number of limitations which make it unsuitable in certain environments. I think a dedicated service account (with locked down firewall rules) in a shared VPC is an acceptable tradeoff.

**Comment by Andor** [comment]
I think the default should be the current implementation with completely separated VPC and networks. But it would be OK if someone really really wants to be able to put all the eggs into one basket.

**Comment by onetwopunch** [comment]
I'll go ahead and get a PR up for this. We also need outputs of the subnet/network as well in case someone does want to put a bastion or firewall rule on that network after Vault is created.
