### ISSUE TITLE
Recommended 0.11 compatible version?

### ISSUE THREAD

**Issue by aodj** [terraform-google-modules/terraform-google-vault#62]
Hi, I'm curious what the recommended version to use for Terraform 0.11 is? I've not been able to move to 0.12 due to blocks in other modules I'm reliant upon, but the README.md doesn't have any guidance on what version to choose.

I took a quick poke around the commits, and I'm guessing 2.1.0, but wanted to get your feel for it before committing.

**Comment by sethvargo** [comment]
2.1.x
