### ISSUE TITLE
Can't run from OSX

### ISSUE THREAD

**Issue by aodj** [terraform-google-modules/terraform-google-vault#63]
OSX doesn't have the `md5sum` tool by default so the `gcpkms-encrypt.sh` script fails to execute successfully.

The tool can be easily installed using `brew install md5sha1sum` but there's no mention of this anywhere.

**Comment by sethvargo** [comment]
What version of OS X? I run OS X and I have md5sum at `/usr/local/bin/md5sum`

**Comment by aodj** [comment]
I'm running 10.14.6 on a new MacBook Pro. I installed it using Homebrew and the script runs without a problem after thatl

**Comment by paddie** [comment]
It is also an issue on 10.15 beta, I had to install one other dependency using brew but I forget which.

**Comment by sethvargo** [comment]
This is good feedback, thanks. We have an open issue in Terraform to support this as a terraform resource, at which point this will cease as an issue. If you figure out what package you installed, I'm happy to document it 😄

**Comment by sethvargo** [comment]
This is no longer relevant with https://github.com/terraform-google-modules/terraform-google-vault/pull/74
