### ISSUE TITLE
Debian 10 upgrade breaks startup script

### ISSUE THREAD

**Issue by guhcampos** [terraform-google-modules/terraform-google-vault#68]
After a successful `terraform apply`, Vault is never installed on the created machine. Inspecting the logs reveals the root problem:

vault-us-east1-jvv9 login: Oct  1 18:29:06 vault-us-east1-jvv9 startup-script: INFO startup-script: E: The repository 'http://packages.cloud.google.com/apt google-cloud-monitoring-buster Release' does not have a Release file.

Taking a look at Google's repository I can see entries for jessie and strech, but not buster, so perhaps a downgrade is necessary.

**Comment by sethvargo** [comment]
Hi @guhcampos 

You're right. I just pushed up 6c04f2ad58e3b41909e57502026445a8ec2cec53 to change the default. You can also force the default to a debian 9 in your configurations because it's a variable (and was a variable before the upgrade). I'll try to release a new version soon.
