### ISSUE TITLE
Issues with LB_IP binding

### ISSUE THREAD

**Issue by moos3** [terraform-google-modules/terraform-google-vault#89]
So I'm not sure how it can bind to an IP on a load balancer when it's not on the machine. This is in the config.hcl file. 

```
  address            = "${lb_ip}:${vault_port}"
```

**Comment by sethvargo** [comment]
Hi @moos3 

Sorry, I'm not sure what you're asking. Can you please explain more?

**Comment by onetwopunch** [comment]
@moos3 Can you please clarify your question? Otherwise I'll go ahead and close this issue by the end of the week.
